"""
Cookie management: check, export and load cookies for yt-dlp.
"""

import os
import http.cookiejar

from core.config import COOKIES_FILE


def check_and_export_cookies():
    """
    Ensure a valid cookies.txt file exists.
    If missing or corrupted, attempt to export from Chrome via browser_cookie3.
    """
    if os.path.exists(COOKIES_FILE):
        try:
            jar = http.cookiejar.MozillaCookieJar(COOKIES_FILE)
            jar.load()
            print("\nCookies file already present and valid.")
            return
        except Exception:
            try:
                os.remove(COOKIES_FILE)
                print(
                    "\nCorrupted cookies file detected and deleted. "
                    "Attempting to recreate..."
                )
            except Exception:
                pass

    # File doesn't exist or was corrupted — try to export from Chrome
    print("\nChecking cookies...")
    print("Cookies allow access to age-restricted videos and private content.")

    try:
        print("\nExporting cookies from Chrome...")
        jar = http.cookiejar.MozillaCookieJar(COOKIES_FILE)

        try:
            import browser_cookie3

            cookies = browser_cookie3.chrome()
            for cookie in cookies:
                jar.set_cookie(cookie)
            jar.save()
            print("Cookies exported successfully from Chrome.")
        except Exception as chrome_err:
            print(f"Error exporting cookies from Chrome: {chrome_err}")
            print("Creating empty but valid cookie file...")

            with open(COOKIES_FILE, "w") as f:
                f.write("# Netscape HTTP Cookie File\n")
                f.write("# https://curl.haxx.se/docs/http-cookies.html\n")
                f.write(
                    "# This file was generated by yt-dlp! "
                    "Edit at your own risk.\n\n"
                )

            print("Empty cookie file created successfully.")
            print(
                "\nWarning: Without valid cookies, "
                "age-restricted videos will not be accessible."
            )
    except Exception as e:
        print(f"Error managing cookies: {e}")


def get_cookies_file():
    """Return the cookies file path if it exists, else None."""
    if os.path.exists(COOKIES_FILE):
        return COOKIES_FILE
    return None
